export type Bike = {
  id: string;
  brand: string;
  model: string;
  year: number;
  km: number;
  price: number | null;
  currency: "EUR" | "RON";
  type: "new" | "used";
  category: "sport" | "touring" | "naked" | "adventure" | "cruiser" | "scooter" | "standard";
  engine: string;
  power: string;
  color: string;
  image: string;
  featured: boolean;
  available: boolean;
  warranty?: string;
};

export const bikes: Bike[] = [
  // ── USED BIKES ───────────────────────────────────────────────────────────────
  {
    id: "ducati-panigale-v4s-2024",
    brand: "Ducati",
    model: "Panigale V4S",
    year: 2024,
    km: 3000,
    price: null,
    currency: "EUR",
    type: "used",
    category: "sport",
    engine: "1103cc V4",
    power: "215 CP",
    color: "Ducati Red",
    image: "/bikes/ducati-panigale-v4s.jpg",
    featured: true,
    available: true,
    warranty: "24 luni",
  },
  {
    id: "ducati-v4-rally-2023",
    brand: "Ducati",
    model: "Multistrada V4 Rally",
    year: 2023,
    km: 12100,
    price: null,
    currency: "EUR",
    type: "used",
    category: "adventure",
    engine: "1158cc V4",
    power: "170 CP",
    color: "Ducati Red",
    image: "/bikes/ducati-v4rally.jpg",
    featured: true,
    available: true,
    warranty: "12 luni",
  },
  {
    id: "ducati-scrambler-2024",
    brand: "Ducati",
    model: "Scrambler 800 GEN2",
    year: 2024,
    km: 3047,
    price: null,
    currency: "EUR",
    type: "used",
    category: "naked",
    engine: "803cc L-Twin",
    power: "73 CP",
    color: "Iconic Black",
    image: "/bikes/ducati-scrambler.jpg",
    featured: true,
    available: true,
    warranty: "24 luni",
  },
  {
    id: "suzuki-hayabusa-2021",
    brand: "Suzuki",
    model: "Hayabusa GEN 3",
    year: 2021,
    km: 3400,
    price: null,
    currency: "EUR",
    type: "used",
    category: "sport",
    engine: "1340cc Inline-4",
    power: "190 CP",
    color: "Metallic Matte Black",
    image: "/bikes/suzuki-hayabusa.jpg",
    featured: true,
    available: true,
    warranty: "12 luni",
  },
  {
    id: "honda-nc750s-2018",
    brand: "Honda",
    model: "NC750 S ABS",
    year: 2018,
    km: 28180,
    price: null,
    currency: "EUR",
    type: "used",
    category: "naked",
    engine: "745cc Parallel Twin",
    power: "54 CP",
    color: "Mat Gunpowder Black",
    image: "/bikes/honda-nc750.jpg",
    featured: false,
    available: true,
    warranty: "12 luni",
  },
  {
    id: "bmw-k1300s-2009",
    brand: "BMW",
    model: "K1300S",
    year: 2009,
    km: 66000,
    price: null,
    currency: "EUR",
    type: "used",
    category: "sport",
    engine: "1293cc Inline-4",
    power: "175 CP",
    color: "Alpine White",
    image: "/bikes/bmw-k1300s.jpg",
    featured: false,
    available: true,
    warranty: "12 luni",
  },
  {
    id: "bmw-f650gs-2008",
    brand: "BMW",
    model: "F650GS Twin",
    year: 2008,
    km: 71000,
    price: null,
    currency: "EUR",
    type: "used",
    category: "adventure",
    engine: "800cc Parallel Twin",
    power: "71 CP",
    color: "Black",
    image: "/bikes/bmw-f650gs.jpg",
    featured: false,
    available: true,
    warranty: "12 luni",
  },
  {
    id: "harley-heritage-2003",
    brand: "Harley-Davidson",
    model: "Heritage Softail",
    year: 2003,
    km: 71000,
    price: null,
    currency: "EUR",
    type: "used",
    category: "cruiser",
    engine: "1450cc Twin Cam",
    power: "67 CP",
    color: "Black",
    image: "/bikes/harley-heritage.jpg",
    featured: false,
    available: true,
    warranty: "12 luni",
  },
  {
    id: "honda-cbf600-2009",
    brand: "Honda",
    model: "CBF600S ABS",
    year: 2009,
    km: 83000,
    price: null,
    currency: "EUR",
    type: "used",
    category: "touring",
    engine: "599cc Inline-4",
    power: "78 CP",
    color: "Silver",
    image: "/bikes/honda-cbf600.jpg",
    featured: false,
    available: true,
    warranty: "12 luni",
  },
  {
    id: "benelli-bn125-2022",
    brand: "Benelli",
    model: "BN125",
    year: 2022,
    km: 37000,
    price: null,
    currency: "EUR",
    type: "used",
    category: "naked",
    engine: "125cc Single",
    power: "11 CP",
    color: "Black",
    image: "/bikes/benelli-bn125.jpg",
    featured: false,
    available: true,
    warranty: "12 luni",
  },
  {
    id: "bmw-f800r-2010",
    brand: "BMW",
    model: "F800R ABS",
    year: 2010,
    km: 54000,
    price: null,
    currency: "EUR",
    type: "used",
    category: "naked",
    engine: "798cc Parallel Twin",
    power: "87 CP",
    color: "Black",
    image: "/bikes/bmw-f800r.jpg",
    featured: false,
    available: true,
    warranty: "12 luni",
  },
  // ── NEW BIKES ─────────────────────────────────────────────────────────────────
  {
    id: "benelli-trk702x-2024",
    brand: "Benelli",
    model: "TRK 702X",
    year: 2024,
    km: 0,
    price: 8000,
    currency: "EUR",
    type: "new",
    category: "adventure",
    engine: "700cc Parallel Twin",
    power: "70 CP",
    color: "Matt Black",
    image: "/bikes/trk702.jpg",
    featured: true,
    available: true,
    warranty: "24 luni",
  },
  {
    id: "ducati-multistrada-v4",
    brand: "Ducati",
    model: "Multistrada V4",
    year: 2024,
    km: 0,
    price: null,
    currency: "EUR",
    type: "new",
    category: "adventure",
    engine: "1158cc V4",
    power: "170 CP",
    color: "Ducati Red",
    image: "/bikes/mtsv4.jpg",
    featured: true,
    available: true,
    warranty: "24 luni",
  },
];

export const brands = [
  { name: "Ducati", slug: "ducati", logo: "/brands/ducati.svg" },
  { name: "Indian", slug: "indian", logo: "/brands/indian.svg" },
  { name: "Benelli", slug: "benelli", logo: "/brands/benelli.svg" },
  { name: "Italjet", slug: "italjet", logo: "/brands/italjet.svg" },
  { name: "Malaguti", slug: "malaguti", logo: "/brands/malaguti.svg" },
  { name: "Lambretta", slug: "lambretta", logo: "/brands/lambretta.svg" },
];

export const testimonials = [
  {
    id: 1,
    name: "Catalin E.",
    role: "Client fidel · 3 motociclete achiziționate",
    text: "Sunt la a treia motocicletă de la ei (cu două buy-back-uri incluse). Foarte mulțumit. Voi reveni cu siguranță.",
    rating: 5,
    avatar: "CE",
  },
  {
    id: 2,
    name: "Boris C.",
    role: "Client",
    text: "Echipa este profesionistă și de ajutor, gata să asiste cu orice problemă sau informație. Recomand cu căldură!",
    rating: 5,
    avatar: "BC",
  },
  {
    id: 3,
    name: "Mihai I.",
    role: "Adventure rider",
    text: "Am închiriat o motocicletă pentru un tur în Ardeal. Moto-ul era perfect pregătit, prețul corect. Voi reveni cu siguranță!",
    rating: 5,
    avatar: "MI",
  },
  {
    id: 4,
    name: "Cristina M.",
    role: "Cumpărătoare de prima dată",
    text: "Ca începătoare, m-au ajutat să aleg motocicleta potrivită fără nicio presiune. O echipă de profesioniști adevărați.",
    rating: 5,
    avatar: "CM",
  },
];

export const teamMembers = [
  {
    name: "Dragomir Aurel",
    role: "Fondator",
    image: "/about/team-bg.jpg",
    initials: "DA",
  },
  {
    name: "Dragomir Alexandru",
    role: "Co-fondator",
    image: "/about/team1.jpg",
    initials: "DA",
  },
  {
    name: "Dragomir Antoniu",
    role: "Co-fondator",
    image: "/about/team2.jpg",
    initials: "DA",
  },
  {
    name: "Bosneagu Claudia",
    role: "Sales Manager",
    image: "/about/team3.jpg",
    initials: "BC",
  },
  {
    name: "Ștefănuț Ionuț",
    role: "Service Manager",
    image: null,
    initials: "SI",
  },
  {
    name: "Nazzal Issam",
    role: "Tehnician Service",
    image: null,
    initials: "NI",
  },
];

export const rentalBikes = [
  {
    id: "bmw-f800gt",
    brand: "BMW",
    model: "F800GT",
    year: 2015,
    km: 71800,
    engine: "800cc",
    image: "/bikes/bmw-f800r.jpg",
    available: true,
  },
  {
    id: "bmw-f800r",
    brand: "BMW",
    model: "F800R",
    year: 2010,
    km: 36000,
    engine: "800cc",
    image: "/bikes/bmw-f800r.jpg",
    available: true,
  },
];

export const contactInfo = {
  phone1: "+40 723 709 939",
  phone2: "+40 727 377 966",
  email: "office@hobbymoto.ro",
  address: "Str. Eliberării, Nr. 2G, Constanța, România (900212)",
  companyName: "SC Impex Troia SRL",
  instagram: "https://instagram.com/hobbymoto.ro",
  facebook: "https://www.facebook.com/pages/category/Motorcycle-Dealership/Hobbymoto-132082656880147/",
  googleMaps: "https://www.google.com/maps/place/Hobbymoto+Srl/@44.1777895,28.624392,17z",
  hours: {
    weekdays: "Lun–Vin: 09:00–18:00",
    saturday: "Sâmbătă: 10:00–15:00",
    sunday: "Duminică: Închis",
  },
};
