export type Bike = {
  id: string;
  brand: string;
  model: string;
  year: number;
  km: number;
  price: number;
  currency: "EUR" | "RON";
  type: "new" | "used";
  category: "sport" | "touring" | "naked" | "adventure" | "cruiser" | "scooter" | "standard";
  engine: string;
  power: string;
  torque?: string;
  weight?: string;
  color: string;
  image: string;
  gallery: string[];
  featured: boolean;
  available: boolean;
  warranty?: string;
  description: string;
  extras?: string[];
};

export const bikes: Bike[] = [
  {
    id: "ducati-panigale-v4s-2024",
    brand: "Ducati",
    model: "Panigale V4 S",
    year: 2024,
    km: 4400,
    price: 21850,
    currency: "EUR",
    type: "used",
    category: "sport",
    engine: "1103cc V4",
    power: "215 CP @ 13.000 rpm",
    torque: "124 Nm @ 9.500 rpm",
    weight: "189 kg",
    color: "Ducati Red",
    image: "/bikes/ducati-panigale-v4s.jpg",
    gallery: ["/bikes/gallery/ducati-panigale-v4s/1.jpg"],
    featured: true,
    available: true,
    warranty: "Garanție Ducati până în mai 2028",
    description: "Motocicletă exclusivă și ultra-performantă care a redefinit toate standardele în clasa superbike. Un singur proprietar din mai 2024. Suspensii Öhlins NIX30 față și TTX36 spate, reglaj electronic. Jante Marchesini din aluminiu forjat. Stare impecabilă tehnic și optic.",
    extras: [
      "Suspensie Öhlins NIX30 față (reglaj electronic)",
      "Amortizor Öhlins TTX36 spate",
      "Jante Marchesini aluminiu forjat",
      "Direcție Öhlins reglaj electronic",
      "Un singur proprietar",
    ],
  },
  {
    id: "ducati-v4-rally-2023",
    brand: "Ducati",
    model: "Multistrada V4 Rally",
    year: 2023,
    km: 12100,
    price: 23500,
    currency: "EUR",
    type: "used",
    category: "adventure",
    engine: "1158cc V4 Granturismo",
    power: "170 CP @ 10.750 rpm",
    torque: "121 Nm @ 8.750 rpm",
    weight: "260 kg",
    color: "Ducati Red",
    image: "/bikes/ducati-v4rally.jpg",
    gallery: Array.from({length: 8}, (_, i) => `/bikes/gallery/ducati-v4rally/${i+1}.jpg`),
    featured: true,
    available: true,
    warranty: "Garanție oficială Ducati până în 2027",
    description: "Motocicleta care a restabilit toate standardele privind siguranța, confortul și nivelul de echipare. Un singur proprietar, stare impecabilă tehnic și optic. Livrare cu revizie efectuată și anvelope noi.",
    extras: [
      "Radar față + spate cu cruise control adaptiv",
      "Detectare unghiuri moarte",
      "Suspensie activă Ducati Skyhook (reglaj electronic)",
      "Frâne Brembo Stylema",
      "Geamantane aluminiu incluse",
      "Ghidon și șa încălzite",
      "Quick shifter sus/jos",
      "Roți tubeless cu spite",
      "Pachete opționale disponibile (~€2.000)",
    ],
  },
  {
    id: "ducati-scrambler-2023",
    brand: "Ducati",
    model: "Scrambler 800 GEN2",
    year: 2023,
    km: 3047,
    price: 9850,
    currency: "EUR",
    type: "used",
    category: "naked",
    engine: "803cc L-Twin",
    power: "73 CP @ 8.250 rpm",
    torque: "65.2 Nm @ 7.000 rpm",
    weight: "176 kg",
    color: "Iconic Black",
    image: "/bikes/ducati-scrambler.jpg",
    gallery: Array.from({length: 7}, (_, i) => `/bikes/gallery/ducati-scrambler/${i+1}.jpg`),
    featured: true,
    available: true,
    warranty: "Garanție oficială Ducati până în iunie 2028",
    description: "Motocicletă într-o stare impecabilă tehnic și optic. Cumpărată nouă în iulie 2024, un singur proprietar. ABS Cornering, control tracțiune, moduri de conducere, iluminare full LED cu DRL. Intervalul de revizie: 12.000 km / 12 luni.",
    extras: [
      "ABS Cornering system",
      "Control tracțiune",
      "2 moduri de conducere",
      "Iluminare full LED cu DRL",
      "Capace ghidon RIZOMA (€80)",
      "Alarmă OE Ducati (€350)",
      "Quick shifter OE Ducati (€265)",
      "Protecție motor SW-Motech (€220)",
    ],
  },
  {
    id: "suzuki-hayabusa-2021",
    brand: "Suzuki",
    model: "Hayabusa GEN 3",
    year: 2021,
    km: 3400,
    price: 14400,
    currency: "EUR",
    type: "used",
    category: "sport",
    engine: "1340cc Inline-4",
    power: "190 CP",
    color: "Metallic Matte Black",
    image: "/bikes/suzuki-hayabusa.jpg",
    gallery: Array.from({length: 8}, (_, i) => `/bikes/gallery/suzuki-hayabusa/${i+1}.jpg`),
    featured: true,
    available: true,
    description: "Cumpărată nouă (0 km) de la dealer autorizat, un singur proprietar. Istoricul service-ului efectuat la reprezentanță Suzuki. Daună cosmetică minoră pe partea dreaptă în urma unui incident. Tobe Akrapovic incluse.",
    extras: [
      "Sistem de evacuare Akrapovic (+ evacuare originală inclusă)",
      "Suport telefon",
      "Protecții laterale motor",
      "Istoric service complet la Suzuki",
    ],
  },
  {
    id: "harley-heritage-2003",
    brand: "Harley-Davidson",
    model: "Heritage Softail Classic",
    year: 2003,
    km: 71000,
    price: 11900,
    currency: "EUR",
    type: "used",
    category: "cruiser",
    engine: "1450cc Twin Cam 88B",
    power: "67 CP",
    color: "Black — Ediție 100 de ani",
    image: "/bikes/harley-heritage.jpg",
    gallery: Array.from({length: 8}, (_, i) => `/bikes/gallery/harley-heritage/${i+1}.jpg`),
    featured: false,
    available: true,
    description: "Ediție aniversară 100 de ani Harley-Davidson. Stare impecabilă din punct de vedere optic, fără zgomote anormale. Anvelope noi (0 km). Funcționează perfect, fără probleme mecanice.",
    extras: [
      "Geamantane originale Harley din piele",
      "Far LED",
      "Parbriz original Harley",
      "Sissy bar original Harley",
      "Anvelope noi (0 km)",
      "Ediție 100 de ani",
    ],
  },
  {
    id: "benelli-bn125-2022",
    brand: "Benelli",
    model: "BN125",
    year: 2022,
    km: 37000,
    price: 2700,
    currency: "EUR",
    type: "used",
    category: "naked",
    engine: "125cc răcire cu aer",
    power: "11.1 CP",
    weight: "142 kg",
    color: "Black",
    image: "/bikes/benelli-bn125.jpg",
    gallery: Array.from({length: 8}, (_, i) => `/bikes/gallery/benelli-bn125/${i+1}.jpg`),
    featured: false,
    available: true,
    description: "Cumpărată nouă de la dealer Benelli Constanța. Toate reviziile efectuate la service autorizat Benelli (verificabil în sistem). Aspect 9/10, stare de funcționare 10/10.",
    extras: [
      "Top case GIVI cu suport de montare",
      "Suport telefon",
      "Istoric service complet la Benelli",
    ],
  },
  {
    id: "bmw-k1300s-2009",
    brand: "BMW",
    model: "K1300S",
    year: 2009,
    km: 66500,
    price: 6000,
    currency: "EUR",
    type: "used",
    category: "sport",
    engine: "1293cc Inline-4",
    power: "175 CP",
    color: "Alpine White",
    image: "/bikes/bmw-k1300s.jpg",
    gallery: Array.from({length: 8}, (_, i) => `/bikes/gallery/bmw-k1300s/${i+1}.jpg`),
    featured: false,
    available: true,
    description: "Livrată cu revizie completă: ulei motor, filtru ulei, ulei transmisie finală și lichid de frână. Anvelope aproape noi (~800-1.000 km). Stare tehnică impecabilă.",
    extras: [
      "Tobe Akrapovic cu omologare",
      "ABS combinat",
      "Control tracțiune",
      "ESA (reglaj electronic suspensie)",
      "Quick shifter OE BMW",
      "Calculator de bord (consum, autonomie)",
    ],
  },
  {
    id: "bmw-f650gs-2008",
    brand: "BMW",
    model: "F650GS Twin",
    year: 2008,
    km: 71000,
    price: 4200,
    currency: "EUR",
    type: "used",
    category: "adventure",
    engine: "800cc Parallel Twin",
    power: "71 CP @ 7.000 rpm",
    color: "Black",
    image: "/bikes/bmw-f650gs.jpg",
    gallery: Array.from({length: 8}, (_, i) => `/bikes/gallery/bmw-f650gs/${i+1}.jpg`),
    featured: false,
    available: true,
    description: "Include revizie completă: ulei, filtru ulei, filtru aer, filtru combustibil. Livrare disponibilă în toată țara. Stare tehnică impecabilă. Anvelope noi montate după fotografiere.",
    extras: [
      "Ghidon încălzit OE BMW",
      "ABS (dezactivabil pentru off-road)",
      "Calculator de bord (consum, viteză medie, indicator treaptă, temperatură exterioară)",
      "Revizie completă inclusă",
      "Transport național disponibil",
    ],
  },
  {
    id: "honda-cbf600-2009",
    brand: "Honda",
    model: "CBF600S ABS",
    year: 2009,
    km: 83000,
    price: 3700,
    currency: "EUR",
    type: "used",
    category: "touring",
    engine: "599cc Inline-4",
    power: "78 CP",
    color: "Silver",
    image: "/bikes/honda-cbf600.jpg",
    gallery: Array.from({length: 8}, (_, i) => `/bikes/gallery/honda-cbf600/${i+1}.jpg`),
    featured: false,
    available: true,
    warranty: "Garanție 6 luni",
    description: "Motocicletă în stare excelentă, fără accidente, complet echipată. Performanță, siguranță și confort — alegere ideală. Revizie la 60.000 km efectuată. Lanț de transmisie nou la 1.500 km.",
    extras: [
      "ABS",
      "Top case SHAD + geamantane laterale GIVI",
      "Protecții SW MOTECH",
      "Indicator treaptă",
      "Alarmă integrată",
      "Lanț nou (1.500 km)",
      "Transport național disponibil",
    ],
  },
  {
    id: "honda-nc750-2018",
    brand: "Honda",
    model: "NC750 S ABS A2",
    year: 2018,
    km: 28180,
    price: 5200,
    currency: "EUR",
    type: "used",
    category: "naked",
    engine: "745cc Parallel Twin",
    power: "54 CP",
    color: "Mat Gunpowder Black",
    image: "/bikes/honda-nc750.jpg",
    gallery: Array.from({length: 8}, (_, i) => `/bikes/gallery/honda-nc750/${i+1}.jpg`),
    featured: false,
    available: true,
    description: "Cumpărată nouă în 2018 de la reprezentanță. Un singur proprietar, stare impecabilă, fără defecte ascunse. Categorie A2. Anvelope Michelin Pilot Road 4 cu ~20-25% uzură.",
    extras: [
      "Geamantane laterale Shad",
      "Protecții motor Givi",
      "Suport navigație teflon",
      "ABS",
      "Compatibil categorie A2",
      "Transport național la cerere",
    ],
  },
  {
    id: "bmw-f800r-2010",
    brand: "BMW",
    model: "F800R ABS",
    year: 2010,
    km: 54000,
    price: 4100,
    currency: "EUR",
    type: "used",
    category: "naked",
    engine: "798cc Parallel Twin",
    power: "87 CP",
    color: "Black",
    image: "/bikes/bmw-f800r.jpg",
    gallery: Array.from({length: 8}, (_, i) => `/bikes/gallery/bmw-f800r/${i+1}.jpg`),
    featured: false,
    available: true,
    description: "Revizie completă efectuată: ulei motor, filtru ulei, filtru aer, rulmenți roți și simering furci. Kit lanț la ~4.000 km. Anvelope cu ~15-20% uzură.",
    extras: [
      "Ghidon încălzit OE BMW",
      "Priză USB 12V",
      "Calculator de bord",
      "ABS",
      "Revizie completă inclusă",
      "Transport național la cerere",
    ],
  },
  // ── NEW BIKES ─────────────────────────────────────────────────────────────────
  {
    id: "benelli-trk702x-2024",
    brand: "Benelli",
    model: "TRK 702X",
    year: 2024,
    km: 0,
    price: 8000,
    currency: "EUR",
    type: "new",
    category: "adventure",
    engine: "700cc Parallel Twin",
    power: "70 CP",
    color: "Matt Black",
    image: "/bikes/trk702.jpg",
    gallery: ["/bikes/trk702.jpg"],
    featured: true,
    available: true,
    warranty: "24 luni",
    description: "Benelli TRK 702X nou, 0 km, garanție 24 luni. Adventure tourer cu motor 700cc twin, perfect pentru ture lungi și off-road ușor.",
    extras: ["Garanție 24 luni", "0 km", "Dealer oficial Benelli"],
  },
  {
    id: "ducati-multistrada-v4-new",
    brand: "Ducati",
    model: "Multistrada V4",
    year: 2024,
    km: 0,
    price: 0,
    currency: "EUR",
    type: "new",
    category: "adventure",
    engine: "1158cc V4",
    power: "170 CP",
    color: "Ducati Red",
    image: "/bikes/mtsv4.jpg",
    gallery: ["/bikes/mtsv4.jpg"],
    featured: true,
    available: true,
    warranty: "24 luni",
    description: "Ducati Multistrada V4 nou. Prețul se stabilește la cerere în funcție de configurație și accesorii dorite.",
    extras: ["Garanție 24 luni", "0 km", "Dealer oficial Ducati"],
  },
];

export const brands = [
  { name: "Ducati",    slug: "ducati",    logo: "/brands/ducati.svg" },
  { name: "Indian",    slug: "indian",    logo: "/brands/indian.svg" },
  { name: "Benelli",   slug: "benelli",   logo: "/brands/benelli.svg" },
  { name: "Italjet",   slug: "italjet",   logo: "/brands/italjet.svg" },
  { name: "Malaguti",  slug: "malaguti",  logo: "/brands/malaguti.svg" },
  { name: "Lambretta", slug: "lambretta", logo: "/brands/lambretta.svg" },
];

export const testimonials = [
  {
    id: 1,
    name: "Catalin E.",
    role: "Client fidel · 3 motociclete achiziționate",
    text: "Sunt la a treia motocicletă de la ei (cu două buy-back-uri incluse). Foarte mulțumit. Voi reveni cu siguranță.",
    rating: 5,
    avatar: "CE",
  },
  {
    id: 2,
    name: "Boris C.",
    role: "Client",
    text: "Echipa este profesionistă și de ajutor, gata să asiste cu orice problemă sau informație. Recomand cu căldură!",
    rating: 5,
    avatar: "BC",
  },
  {
    id: 3,
    name: "Mihai I.",
    role: "Adventure rider",
    text: "Am închiriat o motocicletă pentru un tur în Ardeal. Moto-ul era perfect pregătit, prețul corect. Voi reveni cu siguranță!",
    rating: 5,
    avatar: "MI",
  },
  {
    id: 4,
    name: "Cristina M.",
    role: "Cumpărătoare de prima dată",
    text: "Ca începătoare, m-au ajutat să aleg motocicleta potrivită fără nicio presiune. O echipă de profesioniști adevărați.",
    rating: 5,
    avatar: "CM",
  },
];

export const teamMembers = [
  { name: "Dragomir Aurel",     role: "Fondator",          image: null,              initials: "DA" },
  { name: "Dragomir Alexandru", role: "Co-fondator",       image: null,              initials: "DA" },
  { name: "Dragomir Antoniu",   role: "Co-fondator",       image: null,              initials: "DA" },
  { name: "Bosneagu Claudia",   role: "Sales Manager",     image: "/about/team3.jpg", initials: "BC" },
  { name: "Ștefănuț Ionuț",    role: "Service Manager",   image: null,              initials: "SI" },
  { name: "Nazzal Issam",       role: "Tehnician Service", image: null,              initials: "NI" },
];

export const rentalBikes = [
  {
    id: "bmw-f800gt",
    brand: "BMW",
    model: "F800GT",
    year: 2015,
    km: 71800,
    engine: "800cc",
    image: "/bikes/bmw-f800r.jpg",
    available: true,
  },
  {
    id: "bmw-f800r-rental",
    brand: "BMW",
    model: "F800R",
    year: 2010,
    km: 36000,
    engine: "800cc",
    image: "/bikes/bmw-f800r.jpg",
    available: true,
  },
];

export const contactInfo = {
  phone1: "+40 723 709 939",
  phone2: "+40 727 377 966",
  email: "office@hobbymoto.ro",
  address: "Str. Eliberării, Nr. 2G, Constanța, România (900212)",
  companyName: "SC Impex Troia SRL",
  instagram: "https://instagram.com/hobbymoto.ro",
  facebook: "https://www.facebook.com/pages/category/Motorcycle-Dealership/Hobbymoto-132082656880147/",
  googleMaps: "https://www.google.com/maps/place/Hobbymoto+Srl/@44.1777895,28.624392,17z",
  hours: {
    weekdays: "Lun–Vin: 09:00–18:00",
    saturday: "Sâmbătă: 10:00–15:00",
    sunday: "Duminică: Închis",
  },
};
